name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  VITE_BASE: /arduino-teaching/

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
        env:
          BASE_URL: ${{ env.VITE_BASE }}

      - name: deploy
        run: |
          cd book/.vuepress/dist
          [ -f 404.html ] || ln -s index.html 404.html
          if [ "none" !=  "$cname" ]; then echo "$cname" > CNAME; fi
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"
          git init
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push -f https://_:"$token"@github.com/${{ github.event.repository.full_name }}.git master:gh-pages
        shell: bash
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
          cname: none
